# Generated by Django 4.0.4 on 2022-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_word_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
